/*
 * GianTigle Supermarkets
 * This is a simple supermarket example interface for CS6650 at Northeastern University 
 *
 * OpenAPI spec version: 1.11
 * Contact: i.gorton@northeastern.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.ApiException;
import io.swagger.client.model.ResponseMsg;
import io.swagger.client.model.TopItems;
import io.swagger.client.model.TopStores;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ItemsApi
 */
@Ignore
public class ItemsApiTest {

    private final ItemsApi api = new ItemsApi();

    /**
     * get top 10 items sold at store
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void topItemsTest() throws ApiException {
        Integer storeID = null;
        TopItems response = api.topItems(storeID);

        // TODO: test validations
    }
    /**
     * get top 5 stores for item sales
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void topStoresTest() throws ApiException {
        Integer itemID = null;
        TopStores response = api.topStores(itemID);

        // TODO: test validations
    }
}
